### ISSUE TITLE
UndefinedError: 'page' is undefined

### ISSUE THREAD

**Issue by ralessi** [toni-heittola/bootcase#1]
Hi Toni,

I followed your instructions, that is:
- git clone bootcase under themes/
- put this line in `pelicanconf.py`: `THEME = 'themes/bootcase/'`

But `make publish` fails with:
````
CRITICAL: UndefinedError: 'page' is undefined
make: *** [Makefile:100: publish] Error 1
````
I don't know where to look to fix this. Any suggestions would be much appreciated.

Robert

**Comment by toni-heittola** [comment]
You could run `make html DEBUG=1` to see more info about the error.

**Comment by ralessi** [comment]
Thank you for your help.  With `DEBUG=1` I get the following:
````
CRITICAL: UndefinedError: 'page' is undefined
Traceback (most recent call last):
  File "/usr/bin/pelican", line 11, in <module>
    load_entry_point('pelican==3.7.1', 'console_scripts', 'pelican')()
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 487, in main
    pelican.run()
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/usr/lib/python3.6/site-packages/pelican/generators.py", line 600, in generate_output
    self.generate_pages(writer)
  File "/usr/lib/python3.6/site-packages/pelican/generators.py", line 496, in generate_pages
    self.generate_direct_templates(write)
  File "/usr/lib/python3.6/site-packages/pelican/generators.py", line 444, in generate_direct_templates
    page_name=os.path.splitext(save_as)[0])
  File "/usr/lib/python3.6/site-packages/pelican/writers.py", line 224, in write_file
    page.save_as, override_output)
  File "/usr/lib/python3.6/site-packages/pelican/writers.py", line 171, in _write_file
    output = template.render(localcontext)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/robert/Documents/robertalessi.net/themes/bootcase/templates/index.html", line 1, in top-level template code
    {% extends "page.html" %}
  File "/home/robert/Documents/robertalessi.net/themes/bootcase/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/robert/Documents/robertalessi.net/themes/bootcase/templates/base.html", line 3, in top-level template code
    <html lang="{% block html_lang %}{{ DEFAULT_LANG }}{% endblock %}">
  File "/home/robert/Documents/robertalessi.net/themes/bootcase/templates/page.html", line 3, in block "html_lang"
    {% block html_lang %}{{ page.lang }}{% endblock %}
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'page' is undefined
make: *** [Makefile:100: publish] Error 1
````

**Comment by toni-heittola** [comment]
Are you using `Template: index` somewhere else than page type of content? `index` template is assumed to be page-type in this Pelican-theme.

**Comment by ralessi** [comment]
I am not I daresay, as I am working on a fresh installation of pelican.  Actually, I just have one page in contents/pages, first_page.rst, which is:
````
:Title: My very first page
:Date: 2018-04-29 11:50
:Category: Main

Hello, World!
````

My pelicanconf.py follows:
````
#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = 'Robert Alessi'
SITENAME = 'robertalessi.net'
SITEURL = 'http://www.robertalessi.net/~robert/static'

PATH = 'content'

TIMEZONE = 'Europe/Paris'

DEFAULT_LANG = 'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
         ('Python.org', 'http://python.org/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),
         ('Current site', 'http://www.robertalessi.net'),)

# Social widget
SOCIAL = (#('You can add links in your config file', '#'),
          ('rss', 'feeds/all.atom.xml'),
          ('git', 'http://git.robertalessi.net'),)

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

THEME = 'themes/bootcase/'
````

The standard `notmyidea` theme works.

**Comment by toni-heittola** [comment]
Add these parameters and it should start working:

    DIRECT_TEMPLATES = ['news']
    PAGE_URL = '{slug}'
    PAGE_SAVE_AS = '{slug}.html'
